### ISSUE TITLE
Support react dev-tool? 

### ISSUE THREAD

**Issue by bichikim** [antfu/reactivue#26]
![image](https://user-images.githubusercontent.com/13829322/106737004-7ec69c80-6659-11eb-9da4-db9d9065bb57.png)

**Comment by sibbng** [comment]
Seems working for me. What is your expectation?

I have noticed few thing can be improved.
- defineComponent/createSetup returns Anonymous component/hook. Can be fixed by an argument or babel plugin.
- Setup hook that displayed in hooks pane doesn't have a debug value. That can be provided with useDebugValue.
- Reactivue internals such as tick and instance ids can be labeled with [useDebugValue](https://github.com/facebook/react/issues/16474#issuecomment-582225302) for further readibility.

Not sure but maybe we can:
- List watchers/lifecycle hooks (onMounted, watch, computed) here.
- Disable/Enable that watchers/lifecycle hooks through a boolean.

**Comment by bichikim** [comment]
Sorry The above snapshot is wrong
Showing states in the devtool looks good to use
![image](https://user-images.githubusercontent.com/13829322/107122733-d45eab80-68dc-11eb-842c-a8006843d1c7.png)
